### ISSUE TITLE
SelectableLinkify : SelectableText only supports TextSpan; Other type of InlineSpan is not allowed

### ISSUE THREAD

**Issue by deacon78** [Cretezy/flutter_linkify#82] opened 2021-03-18 09:38 UTC
Hello I have this issue : 

`════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building SelectableText(dirty, state: _SelectableTextState#a9446):
SelectableText only supports TextSpan; Other type of InlineSpan is not allowed
'package:flutter/src/material/selectable_text.dart':
Failed assertion: line 560 pos 12: '() {
      return _controller._textSpan.visitChildren((InlineSpan span) => span.runtimeType == TextSpan);
    }()'
`

My code : 

`SelectableLinkify(
                                    onOpen: (link) async {
                                      if (await canLaunch(link.url)) {
                                        await launch(link.url);
                                      } else {
                                        throw 'Could not launch $link';
                                      }
                                    },
                                    text: this.listeNotes[position].note,
                                    //textScaleFactor: 1.0,//not supported by "SelectableLinkify" :(
                                    style:TextStyle(fontFamily: "BerlinSansFBRegular",fontSize: 10,),
                                    options: LinkifyOptions(humanize: false),//pour afficher le http
                                  ),`

**Comment by MohamedEL-Torky** [comment] 2021-03-18 09:51
Please check #79

**Comment by Cretezy** [comment] 2021-04-12 18:27
This appears to be fixed with https://github.com/Cretezy/flutter_linkify/pull/80, which has a remaining requested change. Will merge ASAP

Duplicate of https://github.com/Cretezy/flutter_linkify/issues/79

**Closed by Cretezy** 2021-04-12 18:27 UTC
